apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  labels:
    app: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      name: load-generator
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: busybox
        command:
        - /bin/sh
        - -c
        - "wget -d --header='Content-Type: application/x-www-form-urlencoded'  --header='Authorization: Basic Zmx1dHRlci1hcHA6TDRneno4RUNCcmRtelA4Q3BnR2VTVmE5' --post-data 'grant_type=password&username=admin&password=12345'   http://backend:443/oauth/token"
