apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: testing
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRESQL_DATABASE : postgres
