kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: testing
  labels:
    type: local
    app: postgres
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: testing
  labels:
    app: postgres
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
